#!/bin/sh

cp arch/arm/boot/zImage ramdisk

cd ramdisk

./repack_bootimg.pl zImage ramdisk-aokp boot.img

sleep 1

zip -0 elementaryAOKP.zip -r META-INF -r system boot.img

sleep 2

adb push elementaryAOKP.zip /sdcard/Kernel

cd ..
