#!/bin/sh

cp arch/arm/boot/zImage ramdisk

cd ramdisk

./repack_bootimg.pl zImage ramdisk-cm9 boot.img

sleep 1

zip -0 cm9kernel.zip -r META-INF boot.img

sleep 2

adb push cm9kernel.zip /sdcard/Kernel

cd ..
