#!/bin/sh

cp arch/arm/boot/zImage ramdisk

cd ramdisk

./repack_bootimg.pl zImage ramdisk-cm9 boot.img

sleep 1

zip -0 elementaryCM9.zip -r META-INF -r system boot.img

sleep 2

./repack_bootimg.pl zImage ramdisk-aosp boot.img

sleep 1

zip -0 elementaryAOSP.zip -r META-INF -r system boot.img

sleep 2

./repack_bootimg.pl zImage ramdisk-aokp boot.img

sleep 1

zip -0 elementaryAOKP.zip -r META-INF -r system boot.img

