#!/bin/sh

make tass_$1_defconfig

make -j 16

sleep 2

cp arch/arm/boot/zImage ramdisk

cd ramdisk

./repack_bootimg.pl zImage ramdisk-cm9 boot.img

sleep 1

zip -0 tass/elementaryCM9-$1.zip -r META-INF -r system boot.img

sleep 2

./repack_bootimg.pl zImage ramdisk-aosp boot.img

sleep 1

zip -0 tass/elementaryAOSP-$1.zip -r META-INF -r system boot.img

sleep 2

./repack_bootimg.pl zImage ramdisk-aokp boot.img

sleep 1

zip -0 tass/elementaryAOKP-ICS-$1.zip -r META-INF -r system boot.img

sleep 2

./repack_bootimg.pl zImage ramdisk-jb boot.img

sleep 1

zip -0 tass/elementaryCM10.1-$1.zip -r META-INF -r system boot.img

sleep 2

cd ..
