#!/system/bin/sh

mount -o rw,remount /system 
mount -o rw,remount /cache

echo 20 > /proc/sys/vm/swappiness

if [ ! -e /cache/swapfile ]
then
	dd if=/dev/zero of=/cache/swapfile bs=1024 count=18432
fi

mkswap /cache/swapfile
chown 0.0 /cache/swapfile
chmod 0600 /cache/swapfile
swapon /cache/swapfile

if [ ! -e /cache/swapfile ]
then
	dd if=/dev/zero of=/system/swapfile bs=1024 count=30720
fi

mkswap /system/swapfile
chown 0.0 /system/swapfile
chmod 0600 /system/swapfile
swapon /system/swapfile
