#!/system/bin/sh

mount -o rw,remount /system 
#mount -o rw,remount /data
mount -o rw,remount /cache

echo 20 > /proc/sys/vm/swappiness

if [ ! -e /cache/swapfile ]
then
	dd if=/dev/zero of=/cache/swapfile bs=1024 count=18432
fi

mkswap /cache/swapfile
chown 0.0 /cache/swapfile
chmod 0600 /cache/swapfile
swapon /cache/swapfile

#if [ ! -e /data/swapfile ]
#then
#	dd if=/dev/zero of=/data/swapfile bs=1024 count=51200
#fi

#mkswap /data/swapfile
#chown 0.0 /data/swapfile
#chmod 0600 /data/swapfile
#swapon /data/swapfile
