#!/system/bin/sh

chmod 644 /dev/frandom
chmod 644 /dev/erandom
chmod 644 /dev/urandom
chmod 644 /dev/random

rm /dev/random && ln /dev/frandom /dev/random
rm /dev/urandom && ln /dev/erandom /dev/urandom

